openapi: 3.0.3
info:
  title: TodoApp
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://127.0.0.1:8000'
paths:
  /api/v1/todos:
    get:
      summary: 'Display a listing of the resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 52
                      title: '안녕하세요?'
                      content: 하하하하
                      deadline: '2021-12-12'
                      isDone: 52
                      updated_at: '28 minutes ago 전에 수정되었습니다.'
                    -
                      id: 51
                      title: '안녕하세요?'
                      content: 하하하
                      deadline: '마감기한이 정해져 있지 않습니다.'
                      isDone: 51
                      updated_at: '30 minutes ago 전에 수정되었습니다.'
                    -
                      id: 2
                      title: Reprehenderit.
                      content: 'Quisquam ipsa dignissimos qui ea ut quis maiores. Sit velit deleniti at est.'
                      deadline: '마감기한이 정해져 있지 않습니다.'
                      isDone: 2
                      updated_at: '1 hour ago 전에 수정되었습니다.'
                    -
                      id: 3
                      title: Eum.
                      content: 'Cum blanditiis voluptas est molestiae ex. Maiores est omnis labore nam atque.'
                      deadline: '마감기한이 정해져 있지 않습니다.'
                      isDone: 3
                      updated_at: '1 hour ago 전에 수정되었습니다.'
                    -
                      id: 4
                      title: 'Iste quae.'
                      content: 'Aut voluptatibus voluptates cum nulla. Eos id et reiciendis numquam placeat.'
                      deadline: '마감기한이 정해져 있지 않습니다.'
                      isDone: 4
                      updated_at: '1 hour ago 전에 수정되었습니다.'
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 11
                    path: 'http://127.0.0.1:8000/api/v1/todos'
                    per_page: 5
                    to: 5
                    total: 51
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 52
                        title: '안녕하세요?'
                        content: 하하하하
                        deadline: '2021-12-12'
                        isDone: 52
                        updated_at: '28 minutes ago 전에 수정되었습니다.'
                      -
                        id: 51
                        title: '안녕하세요?'
                        content: 하하하
                        deadline: '마감기한이 정해져 있지 않습니다.'
                        isDone: 51
                        updated_at: '30 minutes ago 전에 수정되었습니다.'
                      -
                        id: 2
                        title: Reprehenderit.
                        content: 'Quisquam ipsa dignissimos qui ea ut quis maiores. Sit velit deleniti at est.'
                        deadline: '마감기한이 정해져 있지 않습니다.'
                        isDone: 2
                        updated_at: '1 hour ago 전에 수정되었습니다.'
                      -
                        id: 3
                        title: Eum.
                        content: 'Cum blanditiis voluptas est molestiae ex. Maiores est omnis labore nam atque.'
                        deadline: '마감기한이 정해져 있지 않습니다.'
                        isDone: 3
                        updated_at: '1 hour ago 전에 수정되었습니다.'
                      -
                        id: 4
                        title: 'Iste quae.'
                        content: 'Aut voluptatibus voluptates cum nulla. Eos id et reiciendis numquam placeat.'
                        deadline: '마감기한이 정해져 있지 않습니다.'
                        isDone: 4
                        updated_at: '1 hour ago 전에 수정되었습니다.'
                    items:
                      type: object
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 11
                      path: 'http://127.0.0.1:8000/api/v1/todos'
                      per_page: 5
                      to: 5
                      total: 51
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: qecojijmmixynnibhlussaqdznaxngxzsstkqwxqnnmu
                content:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ldalxaoielhxaalvwortpoyyhfmhjlrtebrdiwwixsnitpjqzdmhodubchclytwilexicepuqlzjolufcgoofzozrxuogvmhphetinmaejnzqubgdxktyzjkwlakcxleqchgbbauiyjvkiqhadmczxalsmquwsxjhmpfnyogpdkcpogmtjulkoagvwkrbvnqqbcjcofcvycwuwxziztvravmbcftgvmthkuqwnabixlukwzvmvzovouuamzmhs
                deadline:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2021-08-22T11:21:44'
                isDone:
                  type: boolean
                  description: ''
                  example: false
              required:
                - title
                - isDone
      security: []
  '/api/v1/todos/{id}':
    get:
      summary: 'Display the specified resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: '해당 할일을 찾을 수가 없습니다.'
                properties:
                  message:
                    type: string
                    example: '해당 할일을 찾을 수가 없습니다.'
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: cnoilpkytkikpgxorgniypsxpm
                content:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: pekjnaljrgzpexnalqsugiehcdnxwbngzwxytsgvvfqrw
                deadline:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2021-08-22T11:21:44'
                isDone:
                  type: boolean
                  description: ''
                  example: false
              required:
                - title
                - isDone
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the todo.'
        example: 14
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
